name: Deploy Learn Frenchy to Uberspace
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use Node.js 18 or later

      - name: Install dependencies
        run: npm install

      - name: Build the Svelte app
        env:
          VITE_API_URL: https://french-api.gregorion.net
        run: |
          echo "Building with VITE_API_URL=$VITE_API_URL"
          npm run build

      - name: Deploy using Rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avrh --delete
          path: dist/ # Ensure this points to the output directory of your build
          remote_path: /var/www/virtual/future4/french.gregorion.net
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.SSH_PRIVATE_KEY_PASS }} # Only needed if you added a passphrase upon creating the SSH key
